### ISSUE TITLE
Q, read this when you forget what you need to work on! (TODO LIST)

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/wAlnut#305]
GOAL: Build out Dileep's HTM model to classify CAPTCHAs in Python with a visualization tool in Javascript D3.js

Python HTM model based on Dileep's PhD thesis How the Brain Might Work: A Hierarchical and Temporal Model for Learning and Recognition
- [x] fix main install instructions
- [x] Step 1) Get Mark setup with Github wAlnut repo @markroxor
- [x] Step 2) Read through Dileep's PhD thesis and think 1st principles how to build it
- [x] Step 3) [Issue](https://github.com/WalnutiQ/wAlnut/issues/277)
- [x] Step 4) small # of training examples, what does clean and positive images mean?
- [x] Setup 1 hour meet times for remaining days of the week with Mark

D3.js visualization of important metrics of the HTM model across time including:
- [x] Step 5) [Issue](https://github.com/WalnutiQ/wAlnut/issues/280)

**Comment by quinnliu** [comment]
<img width="644" alt="screen shot 2016-10-24 at 3 09 17 pm" src="https://cloud.githubusercontent.com/assets/2585159/19646880/dac30390-99fb-11e6-9d19-d68a210a49b7.png">
